import { ThemeSwitcher } from '@/platform/components/ThemeSwitcher';

export const Profile = () => (
  <>
    PROFILE PROFILE PROFILE PROFILE PROFILE PROFILE  PROFILE PROFILE PROFILE PROFILE PROFILE PROFILE  PROFILE PROFILE PROFILE PROFILE PROFILE PROFILE  PROFILE PROFILE PROFILE PROFILE PROFILE PROFILE
    <ThemeSwitcher />
  </>
);
